### ISSUE TITLE
Alchemist class skills not showing up

### ISSUE THREAD

**Issue by Brotter24** [PCGen/pcgen#4252] opened 2018-09-17 04:54 UTC
I'm trying to build and Alchemist and it is only showing Fly as a class skill for Alchemist's, instead of Appraise, Craft, Disable Device, Fly, Heal, Knowledge(Arcana), Knowledge(Nature), Perception, Profession, Sleight of Hand, Spellcraft, Survival, and Use Magic Device.

**Comment by LegacyKing** [comment] 2018-09-23 20:40
Unless you've taken an archetype that alters class skills, that should be working. Can you send a character file that shows this issue to HELP@Pcgen.org?

**Comment by LegacyKing** [comment] 2018-09-29 19:41
Unable to reproduce based upon information given. Closing this as "Can't reproduce".

![image](https://user-images.githubusercontent.com/2759875/46249858-00042980-c3e5-11e8-94a7-224fb9967d3f.png)

**Closed by LegacyKing** 2018-09-29 19:41 UTC
Labels: invalid
