### ISSUE TITLE
Racial Subtypes

### ISSUE THREAD

**Issue by scottz657** [PCGen/pcgen#1887] opened 2016-11-22 22:19 UTC
In the latest release, I am unable to select a racial subtype for several different races, namely Dhampirs, and Half-Elves.

**Comment by LegacyKing** [comment] 2016-11-23 05:04
Hi, can you supply a character .pcg file, so I can load the same source you are? Send it to help@pcgen.org.

Thanks

**Comment by scottz657** [comment] 2016-11-27 04:39
Here it is

________________________________

**Comment by LegacyKing** [comment] 2016-11-27 05:06
Where?

**Comment by scottz657** [comment] 2016-11-27 05:09
I have attached the file to this email.

________________________________

**Comment by scottz657** [comment] 2016-11-27 05:30
I can't upload it on github, I can send it by email though check your inbox

**Comment by LegacyKing** [comment] 2016-11-27 05:39
I have... help@pcgen.org -- nothing there yet.

**Comment by LegacyKing** [comment] 2016-11-27 05:59
![image](https://cloud.githubusercontent.com/assets/2759875/20645955/936985ae-b423-11e6-818b-f29344627d4b.png)

So, uh, what is missing again???

**Comment by scottz657** [comment] 2016-11-27 06:16
Idk what's up because this is what I see
![screenshot 1](https://cloud.githubusercontent.com/assets/23664461/20646012/4ceca7ae-b42e-11e6-9211-ae0a6dfdec22.png)

**Comment by LegacyKing** [comment] 2016-11-27 06:34
This tells me the issue is fixed in the latest version. Grab an autobuild, or the 6.07.00 version. Either *should* resolve your issue.

**Closed by LegacyKing** 2016-11-27 06:34 UTC

**Comment by scottz657** [comment] 2016-11-27 06:38
kk thnx
