### ISSUE TITLE
Bad user experience with high DPI and dark theme

### ISSUE THREAD

**Issue by grebenyukaa** [PCGen/pcgen#1760] opened 2016-10-02 18:00 UTC
I use GTK+ look and feel option to make pcgen support DPI 200 with java 8 on arch linux. Everything seems to be in order except the list box control, which is used, for example, for listing the inventory or skills.
See attached screenshot for further explaination.
![204611_02462016](https://cloud.githubusercontent.com/assets/8776486/19022539/aa6137e2-88eb-11e6-9f0e-08cc6a5a6103.png)

Thanks in advance!

**Comment by LegacyKing** [comment] 2016-10-04 03:05
@cpmeister is this a theme we supply?

**Comment by cpmeister** [comment] 2016-10-04 03:26
No really, but this Look and Feel is native to the linux os family. PCGen wasn't designed to look nice in GTK+ due to various limitations. PCGen was designed work well with the Nimbus or Windows Look and feel. Trying to make PCGen look nice in all Look and Feels causes more headache than it is worth so we instead focused on ones that are packaged with the JRE.

**Comment by abbradar** [comment] 2016-10-04 09:09
Unfortunately, Nimbus doesn't support HiDPI monitors so it's very inconvenient (if not impossible) to use PCGen on them with this LaF. FWIW GTK LaF is packaged with JRE and is used automatically on GNOME Linux desktops (and, for example, by PyCharm). It also the only one which supports HiDPI on Linux (with default widgets), So I'd be fery nice to fix at least several usability problems:

* Font color in the list box -- use system default instead of black for non-highlighted (red) items;
* Height of items in the list box -- determine it from the system font size instead of using fixed height.

This should assure basic usability on HiDPI monitors and dark themes, I think. Notice that I don't have knowledge in Java GUI programming so this very likely may be more tricky than it sounds above...

**Comment by abbradar** [comment] 2016-10-04 10:31
![screenshot_2016-10-04_13-26-32](https://cloud.githubusercontent.com/assets/1174810/19070932/acdfe410-8a3e-11e6-8763-23830bfd4639.png)
![screenshot_2016-10-04_13-26-15](https://cloud.githubusercontent.com/assets/1174810/19070933/ace289ea-8a3e-11e6-85c1-34fe39536f8e.png)
![screenshot_2016-10-04_13-25-36](https://cloud.githubusercontent.com/assets/1174810/19070936/aceb9dc8-8a3e-11e6-861a-27fe135a65fd.png)
![screenshot_2016-10-04_13-23-57](https://cloud.githubusercontent.com/assets/1174810/19070934/ace66c86-8a3e-11e6-8574-f6742a915ab3.png)
![screenshot_2016-10-04_13-23-33](https://cloud.githubusercontent.com/assets/1174810/19070935/ace8c5bc-8a3e-11e6-8d6d-fee67ffa679a.png)

As you can see, it's mostly cases of not using system defaults for font sizes and to calculate heights of fields. Also icons are small (which is understandable because they are not vectorized and is a small issue). Apart from that PCGen actually looks okay on a high DPI monitor. I'm using a classic black-on-white theme so issues with using black font colors instead of system ones are not visible here.

**Comment by LegacyKing** [comment] 2017-03-12 08:11
Just an update. Java FX is the only solution we've come up with. Re-writing the Java UI from Java Swing to JavaFX is underway, but stalled. Awaiting anyone with java experience to step forward and assist.

**Comment by grebenyukaa** [comment] 2017-03-12 14:10
I don't say that it's the best solution - maybe this rowHeight setting should be set in some baseclass of all used JTables, but I was unable to find any, so I just replaced every hardcoded row height value I could find with grep -r

**Comment by grebenyukaa** [comment] 2017-03-12 14:38
@LegacyKing I also managed to find out, that the value for QUALIFIED_COLOR, which is used to color text in those table rows, which can also be red or blue, is loaded from the config file legacy.ini from the setting named prereqQualifyColor.

To my mind this is a serious maintainability issue, because there is stored a hex value of what is assumed to be the text color in a target OS. I think it should be stored as string "system" or smth like that, and the parser for this setting should be modified accordingly.

**Comment by LegacyKing** [comment] 2017-06-25 22:09
I've pulled in these changes and these will be included in the 6.07.03 release.

**Comment by LegacyKing** [comment] 2017-07-04 04:35
Hey @grebenyukaa  having an issue where the stats table is completely condensed - rendering the spinboxes too small. Can you take a look at that?

**Comment by LegacyKing** [comment] 2017-07-04 04:35
![image](https://user-images.githubusercontent.com/2759875/27815254-8cce9c82-6037-11e7-8558-d54f5d3cf9be.png)

**Comment by grebenyukaa** [comment] 2017-07-05 14:58
Okay, I'll look into it.

**Comment by kheinzelmann** [comment] 2017-07-06 17:48
Is it possible to do something similar to what was done in the [PostLevelUpDialog](https://github.com/grebenyukaa/pcgen/blob/213003fb5206f6d0382b0856b92f3b5d3b8ea6e0/code/src/java/pcgen/gui2/dialog/PostLevelUpDialog.java#L146) where the row height is based on the preferred size of the JSpinner added to the table?

There is also an issue with the CharacterHPDialog the fifth column has an IntegerEdit input. It actually took me a while to verify this since I have never actually used this dialog box. It shows up when you click the edit button next to your HP on the summary tab.

**Comment by grimreaper** [comment] 2019-01-13 13:33
@kheinzelmann sorry about the delay. Fixing this is certainly possible, but we need more people clueful about how to build UIs. I'm happy to review patches.

**Comment by LegacyKing** [comment] 2019-04-07 08:56
I think we can close this for now. We have some workarounds.

**Closed by LegacyKing** 2019-04-07 08:56 UTC
